### ISSUE TITLE
Ignore default kubernetes namespaces

### ISSUE THREAD

**Issue by MiguelCosme** [rgeraskin/remove-empty-ns-operator#1]
Hi @rgeraskin, first of all I would like to thank you for sharing your tool openly :)

I have a quick question and correct me if I'm wrong but, from the glance I gave to your code the tool doesn't ignore the **default**, **kube-system**, and **kube-public** namespaces, right?

If not, is it possible to add that logic somewhere?

**Comment by rgeraskin** [comment]
hi @MiguelCosme ! Looks like you are right, I'll add an option for "protected" namespaces to the settings and hardcode systems namespaces also.

Thanks for your attention to this small tool :)

**Comment by rgeraskin** [comment]
@MiguelCosme I've decided not to hardcore default namespaces because usually there are a lot of stuff there so operator skips it. But I've added `protectedNamespaces` setting to be able to add any namespace to the list that the operator should skip.

**Comment by MiguelCosme** [comment]
That sounds like a perfect approach to me!
Just tested on a personal cluster and added a few namespaces I actually want to prevent from being deleted and seems to work as intended.

Thank you for this change so quickly ;)
